language: node_js
node_js:
  - "7.7.1"

before_script:
  - psql -c 'create database teachbot_test;' -U postgres && touch .env

before_install:
- npm install -g npm@5

notifications:
  email: false

services:
  - postgresql


